pootle/core/templatetags/core.py, pootle/core/utils/json.py
This improves the way inline JS/JSON is rendered in templates and allows for more compact output (both unpacked and gzipped)
=> Improve Python to JS serialization

pootle/apps/pootle_misc/checks.py, tests/misc/checks.py
Nested placeholders were failing validation which this commit now fixes while
simplifying the overall implementation.
=> Plurr: simplify check and improve coverage

pootle/static/css/navbar.css, pootle/static/js/browser.js, pootle/static/js/common.js, pootle/templates/core/_breadcrumbs.html
This makes resetting the language or project filter more explicit and easy
=> Show 'All Languages' / 'All Projects' in navbar dropdowns

pootle/apps/pootle_language/models.py
With the new browsing table, this is now purely a client-side concern, which
will determine how to best display data.
=> Cleanup: no need to order on full name

pootle/core/markup/fields.py
Admins only can edit these pages, and there are valid use cases for having scripted content there.
=> Markup: allow scripts again in static pages

pootle/apps/pootle_statistics/forms.py, pootle/apps/pootle_statistics/urls.py, pootle/apps/pootle_statistics/views.py, pootle/core/forms.py, pootle/core/views/__init__.py, pootle/core/views/base.py
By factoring out the querystring's path-based view dispatching, we will be able
to reuse it other internal API endpoints too.
These changes generalize how a view accepting a `path` GET parameter can
delegate to other views. Views inheriting from the new `BasePathDispatcherView`
need to declaratively provide the collection of view classes that will be
instantiated and dispatched based on the type of path passed:
* `store_view_class` for paths matching a store
* `directory_view_class` for paths matching a directory
* `language_view_class` for paths matching a language
* `project_view_class` for paths matching an individual project
* `xlanguage_view_class` for paths matching a project resource across
languages
Likewise, all the path parts (language code, project code, directory path and …
=> Factor out path-based view dispatching

pootle/apps/pootle_project/models.py, pootle/apps/pootle_store/urls.py, pootle/apps/pootle_store/views.py, pootle/core/mixins/treeitem.py, pootle/core/views/__init__.py, pootle/core/views/browse.py, pootle/templates/browser/index.html, tests/views/disabled_project.py, tests/views/get_stats.py
This PR fixes the data format the internal API endpoint returns to match the new format we are using since the move to rendering the browsing tables in React.
In order to share the code that shapes the data, it reuses the path-based view dispatching from #73. This means now the internal endpoint doesn't only return stats, but also browsing data as used by the client. This will become very useful when implement browsing without page reloads.
The the structure stats are returned from the cache via `TreeItem` has been simplified to a list too.
Fixes #62.
=> Fix asynchronous stats/browsing data retrieval

pootle/static/js/shared/components/AutoIcon.js
`this.state` was used when it shouldn't in AutoIcons component; this commit moves from state to default properties and calculated internal object properties.
=> AutoIcons: use default props instead of state (fix #65)

pootle/core/markup/fields.py
This fixes an ugly bug when creating and updating static pages' content.
It turns out that Django 1.9 silently introduced a backwards-incompatible change
which implemented `TextField`'s `to_python` method, and forcing coercion to text
there.
Since `MarkupField` subclasses `TextField` but didn't implement `to_python`
(rather `get_prep_value`), `TextField`'s `to_python` was being called when
cleaning the form data, hence coercing the `MarkupField` instance to a string
via its `__unicode__` method, which in turn returns the HTML-rendered version of
the raw text.
Since we want to get the raw text, we need to ensure `to_python` does the same
as before, i.e. use `get_prep_value`'s code.
Refs. https://code.djangoproject.com/ticket/24677
=> MarkupField: implement `to_python`

CHANGES.md, pootle/static/css/editor.css, pootle/static/js/editor/app.js, pootle/templates/editor/_toolbar.html
The feature is hardly used/useful and adds unnecessary complexity.
=> Editor: remove the ability to jump to units by index

CHANGES.md, docs/features/translation_memory.rst, docs/server/settings.rst, pootle/core/views/translate.py, pootle/settings/60-translation.conf, pootle/settings/90-dev-local.conf.sample, pootle/settings/90-local.conf.template, pootle/static/js/editor/app.js, pootle/templates/editor/_scripts.html, tests/views/language.py, tests/views/project.py, tests/views/tp.py
The built-in ES-based TM suffices for Zing's needs.
=> Cleanup: remove support for amaGama TM

CHANGES.md, pootle/static/css/editor.css, pootle/static/js/editor/app.js, pootle/templates/editor/units/edit.html
This PR overhauls the UI for displaying obsoleted units: instead of a popup message, an overlay over the editing row is displayed that prevents further action. The PR builds on top of #93.
=> Editor: rework UI for displaying obsoleted units

pootle/core/templatetags/core.py, pootle/templates/editor/units/edit.html
See extensive description in #105 for more information.
Note that `to_js` needs to be changed to `to_jquery_safe_js` in override template as well.
=> Editor: break apart tags in JS strings (fix #105)

CHANGES.md, pootle/apps/pootle_misc/checks.py, tests/misc/checks.py
The PR adds CDATA sections to the `tags_differ` check, so that they are considered as a single block/tag.
~~In this PR two new checks are added around `CDATA` sections:~~
~~* `cdata_missing`: to ensure `CDATA` sections in source texts are also present in target texts.~~
~~* `cdata_tags_differ`: to ensure potential (X)HTML tags present in source text's `CDATA` sections are not missing in target texts. This reuses the `tags_differ` check.~~
=> Checks around CDATA sections

pytest_pootle/suite.py
This was referring to the old browsing table, which is no more.
=> Tests: remove dead code

tests/settings.py
The 'exports' cache was there for the now gone import/export functionality.
=> Cleanup: remove unused cache

pootle/core/cache.py, pytest_pootle/fixtures/site.py, requirements/tests.txt, tests/settings.py
This almost entirely removes the dependency on a Redis server for testing.
Unfortunately `fakeredis` cannot be used for the 'redis' named cache (used for
revisions), as django-redis' `incr` implementation uses Redis' `eval()` command,
which is unsupported in `fakeredis` for the time being.
The situation might change when django-redis moves away from using `eval()` or
`fakeredis` provides support for `eval()`.
Update: the `'default'` cache requires no cache at all, so moved that to a dummy backend.
=> Tests: use fake Redis client

.codecov.yml
=> Ignore test directories from coverage

.travis.yml
We have no branches named after the 'stable/' prefix.
=> Cleanup: remove non-existant references

requirements/base.txt
The `jsonfield` package was used for the old config module.
=> Requirements: remove unused package

docs/server/settings.rst, pootle/apps/pootle_misc/checks.py, pootle/settings/60-translation.conf, tests/commands/test_checks.py, tests/models/translationproject.py
The source of interchange files can be various, so checkers should rather be
site-wide, as projects can contain files from various sources.
=> Checks: default to a site-wide checker

pootle/core/views/browse.py, pootle/static/js/stats.js, tests/views/disabled_project.py
Since the data is not sorted in the backend, a list doesn't make sense, hence
the switch to a dictionary.
=> Browser: do not store children data in a list

pytest_pootle/fixtures/views.py, tests/views/language.py, tests/views/project.py, tests/views/tp.py
These browse view tests are now tested using snapshots.
=> Cleanup: remove obsolete tests

tests/data/snapshots/test_browse/admin/_language0_.context.json, tests/data/snapshots/test_browse/admin/_language0_project0_.context.json, tests/data/snapshots/test_browse/admin/_language0_project0_store0.po.context.json, tests/data/snapshots/test_browse/admin/_language0_project0_subdir0_.context.json, tests/data/snapshots/test_browse/admin/_language0_project0_subdir0_store4.po.context.json, tests/data/snapshots/test_browse/admin/_projects_.context.json, tests/data/snapshots/test_browse/admin/_projects_project0_.context.json, tests/data/snapshots/test_browse/member/_language0_.context.json, tests/data/snapshots/test_browse/member/_language0_project0_.context.json, tests/data/snapshots/test_browse/member/_language0_project0_store0.po.context.json, tests/data/snapshots/test_browse/member/_language0_project0_subdir0_.context.json, tests/data/snapshots/test_browse/member/_language0_project0_subdir0_store4.po.context.json, tests/data/snapshots/test_browse/member/_projects_.context.json, tests/data/snapshots/test_browse/member/_projects_project0_.context.json, tests/data/snapshots/test_browse/member2/_language0_.context.json, tests/data/snapshots/test_browse/member2/_language0_project0_.context.json, tests/data/snapshots/test_browse/member2/_language0_project0_store0.po.context.json, tests/data/snapshots/test_browse/member2/_language0_project0_subdir0_.context.json, tests/data/snapshots/test_browse/member2/_language0_project0_subdir0_store4.po.context.json, tests/data/snapshots/test_browse/member2/_projects_.context.json, tests/data/snapshots/test_browse/member2/_projects_project0_.context.json, tests/views/browse.py
It turns out the login function wasn't succeeding (`client.login()` doesn't give
any hint of that), and therefore all tests were being run as anonymous.
Note this doesn't only affect snapshot tests, and older tests also suffer from
this when trying to log in registered members: in the fixture they have no
password set, then an unusable password is set by the environment setup,
therefore any attempts to login using the empty string password fail and the
view code will be run as anonymous.
The simple and effective solution is to use the test client's `force_login()`
method, which is available since Django 1.9.
=> Tests: fix login for browse views

pootle/core/models/snapshot.py, tests/models/snapshot.py
Some response contexts might provide a `RequestContext`, so we also need to
account for that.
=> Snapshot: support cleaning `RequestContext`s

pytest_pootle/data/data_dump.json, pytest_pootle/env.py, tests/formats/mozilla_lang.py
It turns out that units created in e.g. FUZZY state were being altered as part
of submission generation, however the attempt to restore such units back to
their original state wasn't being persisted because `markfuzzy()` and
`makeobsolete()` methods only perform changes to the instance, without saving
them.
=> Test env: fix restoring unit state

pootle/core/models/snapshot.py, tests/models/snapshot.py
Windows uses back-slash as a canonical path separator, whereas we use forward slashes to denote snapshot paths.
Without normalization, snapshot tests would fail on Windows as `filepath` and `base_dir` would use different delimiters, and 'The requested file path is out of the data directory.' exception would be raised.
Also, when saving snapshots, we must always force Unix newlines regardless of the platform.
=> Snapshots: make paths and newlines work properly on any platform

pytest_pootle/fixtures/models/project.py, pytest_pootle/fixtures/models/store.py, tests/commands/changed_languages.py, tests/commands/update_stores.py, tests/core/decorators.py, tests/models/directory.py, tests/models/revision.py, tests/models/store.py, tests/models/unit.py, tests/views/get_edit_unit.py
This PR cleans up and fixes some inconsistencies around the old `project0_nongnu` fixture. Each commit contains the specific details.
=> Test: fixes around project fixture

CHANGES.md, pootle/apps/pootle_project/views.py, tests/views/project.py
Even if the access to these URLs is not exhibited anywhere in the UI, they are
still open to anyone with the major risk that it carries for the server. With
this change we limit the access to such views the same way we do for translate
views.
=> Export view: limit access as we do for translate views

docs/server/settings.rst, pootle/core/views/export.py, pootle/settings/50-project.conf, tests/views/project.py, tests/views/tp.py
It also removes the setting as this is not something deployments should be
concerned and thinking about.
=> Export view: limit result set to a sane amount

CHANGES.md, docs/features/terminology.rst, pootle/apps/pootle_store/models.py, pootle/apps/pootle_store/views.py, pootle/apps/pootle_translationproject/models.py, pootle/templates/editor/units/edit.html
This PR removes 3 queries from requests done to the editing widget:
* The code retrieving terminology matches was being called twice from templates, hence doubling the amount of needed queries.
* The local terminology is unused, and this incurs in an extra query per every unit access. In case it's needed, there are better ways to support this feature so for now we better take it away.
=> Optimize terminology access

pootle/core/mixins/treeitem.py
This PR simplifies and cleans up some code within the tree item mixins. There is no functional change, only the logging level of messages has been moved to `DEBUG`, as these include pure debugging information.
=> TreeItem-related minor cleanups

pootle/apps/pootle_store/models.py, pootle/apps/pootle_store/updater.py
This always evaluates to `True`, and it serves no purpose to Zing as it was
added for the import/export app.
=> Cleanup: remove unused `allow_add_and_obsolete` parameter

pootle/apps/pootle_store/constants.py, pootle/apps/pootle_store/models.py, pootle/apps/pootle_store/updater.py, pytest_pootle/fixtures/models/store.py, pytest_pootle/utils.py, tests/models/store.py
This was added in the context of FS code, and now it was always evaluating to
the same value.
=> Store.update: remove unused `resolve_conflict` parameter

pootle/core/views/api.py, tests/core/views.py
This PR implements generic permission handling for `APIView`s, which will come handy for due dates. These need to specify a `permission_classes` member with a list of classes that check permissions. An empty list (the default) means no permission checking.
Permission classes need to implement a `has_permission` method and return a boolean indicating whether the request is permitted to be processed or not. This can be extended in the future to implement object-specific permissions in views.
The PR also includes a few cleanups that helped implement this, along with an exception handler for dispatch methods — this way the permission checking code can raise an exception, and it will be handled transparently. To some extent this shadows the functionality available in the `errorpages` …
=> APIView: implement permission handling

tests/models/submission.py, tests/settings.py, tests/views/unit.py
Avoids getting it in the way. Tests that need to check for it can still
explicitly enable it.
=> Tests: disable captcha for views

pootle/core/views/api.py, pytest_pootle/fixtures/models/user.py, tests/core/views.py
Reuses `get_object()` and doesn't return the previous object as part
of the response.
=> APIView: simplify delete method

pootle/core/views/api.py, tests/core/views.py
Whenever individual objects want to be retrieved, permission handlers will have
a chance to determine whether the request has permission to continue further in
the `has_object_permission` method.
This method works the same way as `has_permission`, but it also receives the
object as the third argument. The return value is the same too, a boolean
indicating whether the request is allowed or not.
=> APIView: support object-specific permission handlers

pootle/forms/fields.py, tests/forms/fields.py
Data being fed to the form field is potentially coming from a JSON
deserialization, and it's very likely timestamps are interpreted as integers.
=> UnixTimeStampField: also accept integers

pootle/core/views/api.py
While forms can override the `save()` method, they don't get access to
request-specific parameters which are needed to determine certain values to be
saved. By providing a simple hook we allow views to override this part without
resourcing to override entire dispatch methods.
=> APIView: allow overriding how forms are saved

pootle/views/api/duedate.py, tests/views/api/duedate.py
As we are always using the current user, the view can provide this data.
=> DueDates: auto-set who made the last change

CHANGES.md, pootle/static/js/admin/app.js, pootle/static/js/package.json, pootle/static/js/shared/components/CodeMirror.js, pootle/static/js/webpack.config.js
This PR upgrades webpack to v2.2 and makes all the required configuration changes. The resulting bundles are a bit smaller due to tree shaking.
Fixes #131.
=> Upgrade to webpack 2

CHANGES.md, pootle/static/js/admin/general/components/LiveEditor.js
This was causing a JS error which prevented the editor from showing up.
=> LiveEditor: remove bogus reference

pootle/migrations/0002_duedate_path_unique.py, pootle/models/duedate.py
So that we ensure a single due date is assigned to a path.
=> DueDate: make internal path unique

pootle/forms/__init__.py, pootle/forms/duedate.py, pootle/views/api/duedate.py, tests/forms/duedate.py
This allows to update due dates without passing redundant data.
=> DueDateForm: require less fields in edit form

pootle/static/js/helpers.js, pootle/static/js/shared/components/TimeSince.js, pootle/static/js/shared/utils/relativeTime.js, pootle/static/js/shared/utils/relativeTime.test.js, pootle/static/js/shared/utils/time.js, pootle/static/js/shared/utils/time.test.js
To avoid confusion, let's operate with timestamps (in JS, milliseconds since
epoch, as opposed to unix timestamps, which indiceate seconds). Therefore, the
function does not accept ISO8601 dates anymore, but conversion is left up to
callers.
=> timeDelta: interface with milliseconds since epoch

pootle/core/utils/json.py
This changes Django's JSON encoder's default, as we are using timestamps
everywhere when sending down serialized dates over the wire. This way, we save
manual formatting here and there.
=> JSONEncoder: serialize dates/times to unix timestamps

tests/data/snapshots/test_duedate_post/admin/_language0_.context.json, tests/data/snapshots/test_duedate_post/admin/_language0_project0_.context.json, tests/data/snapshots/test_duedate_post/admin/_language0_project0_store0.po.context.json, tests/data/snapshots/test_duedate_post/admin/_language0_project0_subdir0_.context.json, tests/data/snapshots/test_duedate_post/admin/_language0_project0_subdir0_store4.po.context.json, tests/data/snapshots/test_duedate_post/admin/_projects_project0_.context.json, tests/data/snapshots/test_duedate_post/admin/_projects_project0_store0.po.context.json, tests/data/snapshots/test_duedate_post/admin/_projects_project0_subdir0_.context.json, tests/data/snapshots/test_duedate_post/admin/_projects_project0_subdir0_store4.po.context.json, tests/data/snapshots/test_duedate_update/admin/_language0_.context.json, tests/data/snapshots/test_duedate_update/admin/_language0_project0_.context.json, tests/data/snapshots/test_duedate_update/admin/_language0_project0_store0.po.context.json, tests/data/snapshots/test_duedate_update/admin/_language0_project0_subdir0_.context.json, tests/data/snapshots/test_duedate_update/admin/_language0_project0_subdir0_store4.po.context.json, tests/data/snapshots/test_duedate_update/admin/_projects_project0_.context.json, tests/data/snapshots/test_duedate_update/admin/_projects_project0_store0.po.context.json, tests/data/snapshots/test_duedate_update/admin/_projects_project0_subdir0_.context.json, tests/data/snapshots/test_duedate_update/admin/_projects_project0_subdir0_store4.po.context.json
The JSON encoder now serializes to unix timestamps instead of to ISO strings.
=> Update snapshots as default serializing changed

pootle/apps/pootle_app/models/directory.py, pootle/apps/pootle_language/models.py, pootle/apps/pootle_project/models.py, pootle/apps/pootle_store/models.py, pootle/apps/pootle_translationproject/models.py, pootle/core/mixins/treeitem.py, pootle/core/models/virtualresource.py
The key doesn't change across objects, and it's always the internal path.
=> TreeItem: refactor cache key retrieval

pootle/apps/pootle_app/models/directory.py, pootle/apps/pootle_store/models.py, pootle/core/mixins/treeitem.py
Removes dead code related to clearing the stats cache and consolidates the logic in a single method.
=> TreeItem: cleanup cache clearing code

pootle/core/mixins/treeitem.py
The `update_parent_cache()` method is unused.
=> TreeItem: remove dead code

pootle/apps/pootle_app/models/directory.py, pootle/apps/pootle_store/models.py, pootle/apps/pootle_translationproject/models.py, pootle/core/mixins/treeitem.py, tests/core/mixins/treeitem.py
This commit renames the `get_parents()` method into `get_parent()` and
returns individual objects instead of lists of objects. Likewise, `None`
is returned for the situation where there are no parents for an item.
Note this very same change was already performed in the past (82740dd),
but the change was reverted to support virtual folders (7a66eae).
=> TreeItem: items have a single parent

pootle/apps/pootle_app/management/commands/dump.py, pootle/core/mixins/treeitem.py
This PR simplifies and refactors (`Cached`)`TreeItem`'s cache key retrieval and creation.
=> TreeItem: cleanup cache key retrieval/creation

CHANGES.md, pootle/apps/contact/forms.py, pootle/apps/contact/views.py, pootle/templates/contact_form/contact_form_subject.txt, requirements/base.txt
This PR fixes the subject line for emails sent via the contact form. Unfortunately this is caused by the incomplete Django 1.10 support of django-contact-form, so some extra code had to be brought to work around that.
=> Contact form: fix subject line

pootle/core/utils/json.py
This is what client-side code expects.
=> JSONEncoder: return timestamps as integers

pootle/core/views/browse.py
It turns out this was incurring in a query being duplicated.
=> Browse views: cache sidebar announcements

pootle/models/__init__.py, pootle/models/stats.py, pytest_pootle/plugin.py, tests/data/snapshots/test_stats_retrieval/_language0_project0_.json, tests/data/snapshots/test_stats_retrieval_dummy/_non_existing_.json, tests/data/snapshots/test_stats_retrieval_no_stats/_language0_project0_.json, tests/models/stats.py
This PR implements a lightweight `Stats` class for easy querying of stats by path, e.g.:
```python
>> stats = Stats('/foo/bar/')
>> stats.total
14794
>> stats.fuzzy
0
>> stats.last_updated
1485306937
```
=> Stats: provide a simple way to retrieve stats by path

pootle/models/duedate.py, pytest_pootle/factories.py, tests/models/duedate.py
When creating/updating/deleting a due date at the project level, the
operation will affect all existing TPs that belong to the project, which
means that these will take over any language-specific due dates that
might have existed before.
This change will also considerably improve querying due dates for
particular languages.
=> Due dates: propagate project changes to TPs

pootle/static/js/shared/utils/url.js, pootle/static/js/shared/utils/url.test.js
This is a port of the backend's path splitting function so we can use it
to easily and reliably split internal paths into manageable parts, which
can then be leveraged for path and URL generation purposes.
=> URL utils: implement internal path split utility

pootle/models/duedate.py, tests/models/duedate.py
The previous was buggy as it would update/delete due dates for all
resources in a TP.
=> Due dates: ensure propagation only affects current resources

pootle/forms/task.py, pootle/static/js/admin/duedates/components/DueDateContainer.js, pootle/static/js/browser/components/PendingTaskContainer.js, pootle/static/js/shared/api/TaskAPI.js, pootle/static/js/stats.js, pootle/views/api/task.py, tests/data/snapshots/test_get_tasks/admin/context.json, tests/data/snapshots/test_get_tasks/member/context.json, tests/data/snapshots/test_get_tasks_permissions/admin/context.json, tests/data/snapshots/test_get_tasks_permissions/member/context.json
Whenever due dates are updated from the browsing pages, the list of
tasks visible at the top will be refreshed.
This operation involves the `DueDateContainer` and
`PendingTaskContainer` components, however these currently share no
common ancestor because they are rendered independently. Therefore,
in this commit communication across components happens via the
`PTL.stats` module, however it should be noted that this is a temporal
solution and we should merge the afore-mentioned containers so that
everything is rendered below the same rendering tree.
=> Due dates: refresh list of pending tasks upon modifications

pootle/forms/task.py
When refreshing the list of tasks, this ensures at least 3 tasks will be
retrieved when available.
=> DueTaskForm: try to get at least 3 tasks

pootle/core/models/snapshot.py, pootle/models/duedate.py, pootle/models/task.py, pootle/static/js/browser/components/TaskItem.js, pootle/static/js/browser/components/TaskList.js, pytest_pootle/factories.py, tests/models/task.py
This is necessary so that due dates can be directly modified from the
list of tasks.
=> Pending tasks: also provide due date ID to the client

pootle/static/js/shared/components/Dropdown.js
Instead of checking for the presence of an element in the DOM, this
approach will keep track of a flag upon mousedown/mouseup. It is more
robust because elements can be removed from the dropdown's DOM due to
click interactions.
=> Dropdown: make clicking outside behavior more robust

pootle/apps/pootle_misc/context_processors.py, pootle/static/js/admin/duedates/components/DueDatePicker.js, pootle/static/js/shared/utils/time.js, pootle/templates/layout.html
Whenever a day is selected via react-day-picker, the `day` object
provided by the library is set to `12:00:00` in the client's local time.
In order to dynamically display the proper server time the selected day
represents, the client-side date needs to be:
* Adjusted to the server's timezone
* Set to 9:00 in the server's timezone
This requires knowledge of the UTC offset in the client, as well as some
timezone arithmetic which is now done via a couple utility functions.
Implementation note: this hasn't been implemented as a specialized
subclass of `Date` (e.g. `ServerDate`) because subclassing of native
types is limited to pure ES6 environments, and hence transpiling
wouldn't allow us to get there.
Refs. https://babeljs.io/docs/usage/caveats/#classes
=> DueDatePicker: fix display of timezones

pootle/static/js/admin/duedates/components/DueDateContainer.js, pootle/static/js/admin/duedates/components/DueDateWidget.js, pootle/static/js/shared/components/Dropdown.js, pootle/static/js/shared/components/DropdownMenu.js, pootle/static/js/shared/components/DropdownToggle.js
This PR changes the due date administration widget so that the dropdown is closed upon submission. In order to do that, state had to be lifted up, and the dropdown component has been reworked to be fully controlled and read the open state via props.
=> Due dates: close dropdown upon submission

pytest_pootle/fixtures/models/store.py, tests/models/store.py
The explicitness of keyword arguments helps more than the implicitness
of positional arguments. This is especially true when dealing with many
arguments at a time.
=> Cleanup: make it easier to understand some fixtures/tests

pootle/apps/pootle_app/management/commands/__init__.py, pootle/apps/pootle_app/management/commands/sync_stores.py, pootle/apps/pootle_app/management/commands/update_stores.py
The `handle_store` hook is unused and never called:
* for `sync_stores`, the `handle_all_stores` takes over
* for `update_stores`, the `handle_translation_project` method always
returns a falsy value, and no store-specific methods will be executed.
=> Cleanup: remove dead code from update/sync commands

pootle/apps/pootle_store/diff.py, tests/models/store.py
This PR splits the `DiffableStore` into `FileStore` and `DBStore` classes and moves the querying logic that belongs to specific classes away from `DiffableStore`. With docstring additions and other minor cleanups, it should now be easier to follow along the code path.
=> Cleanup on diffable classes

Makefile, pootle/settings/10-base.conf
This makes Makefile compatible with proxy `zing` script
that deals with virtualenv internally.
Also, don't make the trailing slash a part of ASSETS_DIR
for consistency with other variables. Use separator slash
explicitly in the paths that use ASSETS_DIR.
@julen please review/merge
=> Always assume assets are under pootle/assets directory

pootle/apps/pootle_store/syncer.py, pytest_pootle/utils.py, tests/models/submission.py
These were used in the past for upload file merging and import/export.
=> Cleanup: remove unused PO headers

pytest_pootle/fixtures/models/store.py
Now it's next to the other test data.
=> Cleanup: move default store setup to a more sensible place

CHANGES.md, pootle/apps/pootle_store/diff.py, pootle/apps/pootle_store/models.py, pootle/apps/pootle_store/updater.py, tests/models/store.py, tests/models/unit.py
This PR implements the 2nd approach described in https://github.com/evernote/zing/issues/246#issuecomment-290708709 in order to ensure obsolete units that were changed since the last sync don't stay in limbo when they should be resurrected.
Fixes #246.
=> Bugfix: resurrect updated obsolete units (2nd approach)

CHANGES.md, pootle/static/js/browser/components/DetailedStats.js, pootle/static/js/browser/components/TranslationState.js
When zero, the backend strips the amount of translated words, hence we
need to provide a default value.
We now also safeguard for missing last action data.
=> Browser: fix visiting fully untranslated stores

pootle/forms/task.py, pootle/static/js/browser/components/PendingTaskContainer.js, pootle/static/js/shared/api/TaskAPI.js, pootle/views/api/task.py
Retrieving via an offset would be problematic if the list of tasks
changed out of the scope of the current tab, hence providing incorrect
data.
Fixes #256.
=> Tasks: ensure loading more retrieves fresh items

CHANGES.md, pootle/static/js/shared/utils/i18n.js
In older Android+Webkit browsers, the timezone might be reported as an
abbreviation (e.g. 'CET'), but Intl formatting functions require timezone
names as they appear in the IANA DB.
This broke scripts altogether, so now we detect this scenario and fall
back to the server timezone to work around it.
=> i18n: avoid timezone breakage in older Android Webkit browsers

requirements/base.txt
In master tests broke because `requests` updated to `urllib3` to 1.22, and some other dependency (not sure which one) requires `urllib3 < 1.22`.
=> requirements: pin urllib3 to avoid breakage

CHANGES.md, pootle/apps/pootle_app/views/admin/dashboard.py, pootle/templates/admin/dashboard.html
Even if cached, calculating these numbers adds unnecessary extra load on
the server, as the numbers provided there are of no regular use.
=> Admin dashboard: remove expensive server statistics

CHANGES.md, pootle/apps/accounts/views.py
When the sign in view was switched to be customized via Allauth's own
form overridding method in 38f7e27, that made `SignInForm` to be used
all the time.
This can be explained by checking the parent Allauth-provided
`LoginView`'s logic to retrieve the form class to use:
> return get_form_class(app_settings.FORMS, 'login', self.form_class)
which will always give preference to the overriden login form specified
in the settings.
This commit modifies `SocialVerificationView` so that we ensure
`SocialVerificationForm` will always be used.
=> SocialVerificationView: ensure the right form is used

pootle/apps/pootle_misc/util.py
`get_max_month_datetime()` is buggy because it takes no DST transitions
into account: it simply increases 31 days, which should bring the date
to the next month. However, then date is localized to the server
timezone, which will shift the date to a different month and day when
there's a negative DST transition involved. Finally, the code will go
back 1 microsecond, incorrectly assuming the date refers to the first
day of the *next* month.
Because no DST transition is being taken into account, the calculated
end-of-the-month date would refer to the first day of the *current*
month when the month incurred in a DST transition, which would leave the
final date one month behind the expected result.
On the contrary, the new approach is reliable: by using the calendar
module the last day of the …
=> get_date_interval: reliably set the upper bound of the month

tox.ini
Some statements are duplicated and no root access is required.
=> Travis: simplify DB setup

pootle/static/js/.babelrc, pootle/static/js/package.json, pootle/static/js/webpack.config.js
This is encouraged over using ES201x presets.
Note we now require a separate UglifyJS plugin, because the one shipped
in the current stable version of Webpack doesn't understand ES201x
syntax. This will change starting in Webpack 4.0.
=> Webpack: switch to babel-preset-env

pootle/static/js/editor/UnitList.js, pootle/static/js/editor/app.js
This one's more explicit than the previous solution.
=> Editor: force-go instead of relying on implicit state

CHANGES.md, docs/server/optimization.rst, docs/server/settings.rst, pootle/apps/accounts/models.py, pootle/apps/pootle_app/models/permissions.py, pootle/apps/pootle_language/models.py, pootle/apps/pootle_misc/context_processors.py, pootle/apps/pootle_project/models.py, pootle/apps/pootle_store/fields.py, pootle/apps/pootle_translationproject/models.py, pootle/checks.py, pootle/core/constants.py, pootle/settings/20-backends.conf, pootle/settings/30-site.conf, pootle/settings/40-apps.conf, pootle/settings/60-translation.conf, pootle/settings/90-local.conf.template, pootle/static/js/auth/index.js, pootle/templates/editor/export_view.html, pootle/templates/editor/units/edit.html, pootle/templates/help/quality_checks.html, pootle/templates/layout.html
Some unused settings have been removed:
* `POOTLE_META_USERS`
There have been simplifications too:
* `POOTLE_CONTACT_ENABLED` has been removed, in favor of using an email in `POOTLE_CONTACT_EMAIL`
And others have been moved to constants:
* `PARSE_POOL_CULL_FREQUENCY`, `PARSE_POOL_SIZE`
* `POOTLE_CACHE_TIMEOUT`
=> Settings: consolidate and remove unused

CHANGES.md, Makefile, docs/server/commands.rst, pootle/static/js/package.json, pootle/static/js/webpack.config.js
Now that extra customization of the build pipeline is not needed, we can
remove the wrapper command around webpack.
If we need further integration or customization abilities in the future,
we should revisit the entire process, as the previous approach was
overly too complex.
=> Webpack: convert into an npm script

Makefile
Otherwise docusaurus commands won't be available
=> Docs: ensure to install dependencies before building

CHANGES.md, pootle/static/js/editor/components/Editor.js, pootle/static/js/editor/containers/EditorContainer.js
The format and hence the textarea component to be used needs to be
calculated up-front in the container, and not in the editor component
based on current values' state. This caused components to be swapped as
translators typed, totally missing any internal state.
=> Editor: avoid swapping textareas based on current values

.codecov.yml
Apparently the config key value changed from `off` to `false`.
=> Codecov: disable PR comments

pootle/apps/reports/models/invoice.py, tests/models/invoice.py
The `should_add_correction()` method was returning `True` even if adding
a correction wasn't necessary. This didn't have side-effects because
`add_correction()` was safeguarded with a `get_or_create()` call,
however that code-path shouldn't have been hit in that case.
Still, this broke a test -- why this issue didn't manifest before
remains a mystery. The contents of the failing test didn't make much
sense and it has been adjusted accordingly.
Historical note: my feeling is the first time the invoicing code was
ported, the test made sense, but afterwards (and probably in an amended
commit, which could have happened right before merging the feature after
a long hiatus) subtotals were added to the mix, which slightly changed
the logic.
=> Invoices: explicitly check if a correction exists

CHANGES.md, pootle/apps/pootle_app/forms.py
This fixes an issue that prevented from saving changes to users that
didn't indicate Linkedin account details.
=> User: `linkedin` field can be `None` too

.travis.yml, pootle/static/js/package.json, pootle/static/js/webpack.config.js, requirements/travis.txt, tests/models/invoice.py, tox.ini
Setting a flag in `babel-preset-env` seems to be required now when newer packages are pulled.
=> Bugfix: fix UglifyJS

pootle/static/js/webpack.config.js
Let's remove this for now because it's producing inconsistent results
across the board and better err on the side of caution.
=> babel-preset-env: avoid target-specific building

CHANGES.md, pootle/static/js/editor/Unit.js, pootle/static/js/editor/UnitList.js
This fixes a bug where the view rows wouldn't be considered as fuzzy
until their full data was provided after visiting their edit views.
=> Editor: provide fuzzy data when initializing units

CHANGES.md, pootle/apps/staticpages/views.py
The modelform referenced a no-longer existing field, which made the form
generating code crash.
=> StaticPages: fix adding new pages

CHANGES.md, pootle/static/js/editor/app.js, pootle/static/js/shared/components/KeyboardHelpDialog.js, pootle/templates/editor/units/edit.html
The previous way didn't work consistently across browsers.
=> Editor: implement shortcut for copying text from source

pootle/apps/pootle_misc/util.py, pootle/apps/reports/models/invoice.py, tests/models/invoice.py, tests/utils/date.py
Currently these were being omitted. Reporting of the remaining balance has been improved too.
=> Invoices: add support to carry-over negative balances

pootle/templates/invoices/no_invoice_message.html
The reason for a carry-over can now be negative balance too (previously
it'd only be not reaching the minimal payment amount).
=> Invoices: adjust carry-over wording

CHANGES.md, pootle/core/initdb.py
So that they are more restrictive for new installations.
=> Adjust default permissions

CHANGES.md, pootle/apps/accounts/models.py
In some cases the DB might be hit multiple times because values are not
cached yet. With this change, we ensure the SQL queries will be
identical for a particular day, and as such at least the SQL cache can
be used.
=> Top scorers: consider full days starting at midnight

CHANGES.md, pootle/apps/pootle_misc/checks.py, tests/misc/checks.py
The list of available quality checks doesn't include language-specific
checks, and with that, the information provided for the quality check is
incomplete (e.g. missing `is_critical` field).
Given TTK's nature, retrieving language-specific check information would
be way too complicated for the benefit it'd provide (especially given
that there are no language-specific checks which are critical), and
hence we'll simply provide the checks `name` and the `title` unchanged,
and use a `is_critical` value of `False`.
=> Checks: avoid breakage with language-specific checks

pootle/apps/pootle_app/management/commands/build_assets.py, pootle/settings/40-apps.conf
Also switches to using a manifest file, which should make things smoother and more predictable.
=> Fix building assets upon installation

pootle/core/decorators.py, tests/core/decorators.py
The redirect logic was applying to non-XHR requests, and in that context
there's no request being made to this endpoint.
=> Cleanup: remove dead code

pootle/forms/task.py
Reason: sometimes we have more tasks, and it makes sense to allow
to see them all
=> Remove an artificial limit of 10 tasks

pootle/apps/accounts/adapter.py
=> allauth: don't break if `data` kwarg is provided

CHANGES.md, pootle/apps/pootle_language/models.py
The full language list wasn't being invalidated whenever there were
changes to existing languages.
=> Bugfix: invalidate all languages list too

CHANGES.md, pootle/apps/pootle_misc/checks.py, tests/data/snapshots/test_translate/admin/_language0_project0_translate_.context.json, tests/data/snapshots/test_translate/admin/_language0_project0_translate_empty_dir0_.context.json, tests/data/snapshots/test_translate/admin/_language0_project0_translate_empty_dir1_store6.po.context.json, tests/data/snapshots/test_translate/admin/_language0_project0_translate_store0.po.context.json, tests/data/snapshots/test_translate/admin/_language0_project0_translate_subdir0_.context.json, tests/data/snapshots/test_translate/admin/_language0_project0_translate_subdir0_store4.po.context.json, tests/data/snapshots/test_translate/admin/_language0_translate_.context.json, tests/data/snapshots/test_translate/admin/_projects_project0_translate_.context.json, tests/data/snapshots/test_translate/admin/_projects_project0_translate_empty_dir1_store6.po.context.json, tests/data/snapshots/test_translate/admin/_projects_project0_translate_store0.po.context.json, tests/data/snapshots/test_translate/admin/_projects_project0_translate_subdir0_.context.json, tests/data/snapshots/test_translate/admin/_projects_project0_translate_subdir0_store4.po.context.json, tests/data/snapshots/test_translate/admin/_projects_translate_.context.json, tests/data/snapshots/test_translate/member/_language0_project0_translate_.context.json, tests/data/snapshots/test_translate/member/_language0_project0_translate_empty_dir0_.context.json, tests/data/snapshots/test_translate/member/_language0_project0_translate_empty_dir1_store6.po.context.json, tests/data/snapshots/test_translate/member/_language0_project0_translate_store0.po.context.json, tests/data/snapshots/test_translate/member/_language0_project0_translate_subdir0_.context.json, tests/data/snapshots/test_translate/member/_language0_project0_translate_subdir0_store4.po.context.json, tests/data/snapshots/test_translate/member/_language0_translate_.context.json, tests/data/snapshots/test_translate/nobody/_language0_project0_translate_.context.json, tests/data/snapshots/test_translate/nobody/_language0_project0_translate_empty_dir0_.context.json, tests/data/snapshots/test_translate/nobody/_language0_project0_translate_empty_dir1_store6.po.context.json, tests/data/snapshots/test_translate/nobody/_language0_project0_translate_store0.po.context.json, tests/data/snapshots/test_translate/nobody/_language0_project0_translate_subdir0_.context.json, tests/data/snapshots/test_translate/nobody/_language0_project0_translate_subdir0_store4.po.context.json, tests/data/snapshots/test_translate/nobody/_language0_translate_.context.json, tests/misc/checks.py
This accounts for single line breaks, double line breaks, and
3+ line breaks.
Fixes #410.
=> Checks: implement line break checks

CHANGES.md, pootle/static/css/editor.css, pootle/static/js/editor/app.js
This works for links in unit comments marked to be opened in a `_preview` target window. Opened links will be higlighted and navigating to new units will update the contents of the preview window, should it be open.
Fixes #411.
=> Editor: implement auto-updating preview windows

CHANGES.md, docs/ref-commands.md, pootle/apps/pootle_app/management/commands/__init__.py, pootle/apps/pootle_app/management/commands/refresh_stats.py
All existing projects can still be refreshed using the
`--include-disabled-projects` flag, and individual projects can also be
targetted via the `--project` argument.
Fixes #421.
=> refresh_stats: don't process disabled projects by default

pootle/core/mixins/treeitem.py
In the context of `refresh_stats`, directories with a large number of
stores end up doing a lot of unnecessary work, because each store
enqueue a job to calculate its stats, plus another job to calculate its
parent directory stats.
Such directories will attempt to concurrently work on calculating the
stats for the same item, and waste tons of resources.
With this commit, we will:
1. skip any stats calculation if the amount of pending jobs for that
item is > 1, i.e. bail out because other jobs will work on it
later on.
2. decrease the dirty counter in the item and in all parent path trail
items to mark the job as processed.
The speed-up is substantial. When processing a directory with 583 stores
in a machine where 4 CPU cores are available and using 4 workers, we
decreased the processing …
=> refresh_stats: skip doing extra unnecessary work

pootle/core/mixins/treeitem.py
This reverts commit a5e1588c30068270790a02760b7738993d710795.
It turns out accessing the dirty score this way is not atomic, hence it
is unreliable when running with multiple worker processes. We'll revert
that changeset for the time being.
=> Revert "refresh_stats: skip doing extra unnecessary work"

CHANGES.md, pootle/apps/pootle_store/unit/search.py
In some cases, units couldn't be accessed because the index in the list
of UIDs would end up being a float. We will forcedfuly use integer
division for calculating indexes now.
=> Bugfix: do not break access to individual units

CHANGES.md, pootle/templates/help/quality_checks.html, setup.py
Because Zing uses its own set of checks already. Moreover, the page that
was trying to be included broke the page altogether because since Django
2.1 exceptions raised in templates are not silenced.
Fixes #431.
=> Checks: do not include TTK quality checks page

pootle/core/mixins/treeitem.py, tests/core/mixins/treeitem.py
* Makes `CachedMethods` an enum and adds tests
* Adds some `CachedTreeItem` tests
=> Improve treeitem module's test coverage

CHANGES.md, pootle/core/mixins/treeitem.py, tests/data/snapshots/test_browse/admin/_language0_.context.json, tests/data/snapshots/test_browse/admin/_projects_.context.json, tests/data/snapshots/test_stats_checks/admin/_language0_.response_body.json, tests/data/snapshots/test_stats_checks/admin/_projects_.response_body.json, tests/data/snapshots/test_stats_checks/member/_language0_.response_body.json, tests/data/snapshots/test_stats_checks/nobody/_language0_.response_body.json
This fixes a bug where language pages wouldn't display any total numbers
if there were disabled projects without calculated stats (note this is
now the default for `refresh_stats`).
In a follow-up change we'll need to make sure this behavior can be
toggled so that browsing views can still get the total counts that
include disabled projects.
Refs. #425.
=> Language: do not count disabled items for totals

docs/start-installation.md, website/package.json, website/version.sh
This will replace any occurrences of |version| in the Markdown documents
in docs/ with the actual Zing version number.
=> Docs: preprocess version from package.json

pootle/core/url_helpers.py, tests/core/url_helpers.py
Plus extra parametrized tests.
=> get_editor_filter: add support for `all` query string

pootle/static/js/shared/utils/url.js, pootle/static/js/shared/utils/url.test.js
Some of the URLs being generated included two consecutive slashes. This change makes `getTranslateUrl()` more robust by internally leveraging `splitPootlePath()`.
=> getTranslateUrl: fixes to avoid double slashes

.travis.yml
Builds have been unreliable lately (had to manually empty caches more often than not), so let's experiment with these changes:
* Travis now automatically caches npm dependencies
* Let's cache pip dependencies too
=> Travis: adjustments around Travis cache

.travis.yml
There's no need to pass environment variables via `bash -c` because this
is already set by Travis. Likewise, we can resource to using `python
manage.py` all the time to avoid an extra `init` command.
=> Travis: simplify project config

pootle/static/js/browser/components/BrowserTableRow.js, pootle/static/js/browser/components/FailingChecksTable.js, pootle/static/js/browser/components/TaskItem.js, pootle/static/js/browser/components/TranslateActions.js, pootle/static/js/shared/utils/url.js, pootle/static/js/shared/utils/url.test.js
* URLs for individual checks were not properly generated
* URLs for check categories can now be generated
* All code now leverages `getTranslateUrl()`
=> Fix a bunch of frontend translate URLs

CHANGES.md, pootle/apps/pootle_store/views.py, pootle/static/js/editor/components/UnitSource.js, pootle/static/js/editor/index.js, pootle/static/js/utils.js, pootle/templates/editor/units/edit.html
* Placeables are not actionable in read-only mode anymore
* Without edit rights, the backend won't provide non-actionable items (terminology, TM)
Fixes #460.
=> Editor: deactivate placeables in read-only mode

pootle/static/js/editor/containers/EditorContainer.js, pootle/static/js/editor/utils/strings.js
Allows for a wider set of tokens to be handled by Plurr
=> Fix evernote#468: Support Plurr preview for simple placeholders

pootle/templates/help/_pootle_quality_checks.html
=> Add descriptions for line break-related checks

pootle/constants.py, pootle/static/js/package-lock.json, pootle/static/js/package.json
This is not a version bump. This is to align the version with the latest git release.
=> Fix outdated Zing version number
