Evernote/zing

- pootle/apps/pootle_store/fields.py
- pootle/apps/pootle_store/models.py
- pootle/core/utils/multistring.py
- tests/core/utils/multistring.py
This PR factors out some multistring-related code and adds tests for it.
> Cleanup: refactor and test multistring parsing/unparsing

- pootle/apps/pootle_misc/checks.py
- tests/misc/checks.py
Also added more tests to cover occurrences like this.
> Plurr: fix placeholder check with semicolons

- pootle/static/css/actions.css
- pootle/static/css/breadcrumbs.css
- pootle/static/css/editor.css
- pootle/static/css/navbar.css
- pootle/static/css/scores.css
- pootle/static/css/style.css
- pootle/static/js/browser.js
- pootle/static/js/dropdown.js
- pootle/templates/browser/base.html
- pootle/templates/core/_breadcrumbs.html
- pootle/templates/layout.html
- pootle/templates/staticpages/page_display.html
- Consolidate extra header/footer links in the menu
- Get rid of footer
- Move breadcrumbs over to the navbar
- Make the stats bar below the navbar ~30% more compact
- Get rid of JS code that changed geometry of the dropdown menu and breadcrumbs
> Change styling of headers/footers

- pootle/static/css/style.css
- pootle/static/js/browser/components/ColoredNumber.js
- pootle/static/js/browser/components/NumberPill.js
- pootle/static/js/stats.js
A bunch of styling-related fixes mostly related to displaying browser table stats
> Styling Fixes

- pootle/static/js/common.js
- pootle/static/js/editor/app.js
- pootle/static/js/search.js
- pootle/static/js/shared/components/KeyboardHelpDialog.css
- pootle/static/js/shared/components/KeyboardHelpDialog.js
Implement Mac-compatible shortcuts and keyboard help dialog
> Keyboard dialog and shortcuts

- pootle/static/css/buttons.css
- pootle/static/css/editor.css
- pootle/static/css/navbar.css
- pootle/static/css/scores.css
- pootle/static/css/style.css
- pootle/templates/browser/base.html
- pootle/templates/core/_breadcrumbs.html
- pootle/templates/editor/_toolbar.html
- pootle/templates/layout.html
Misc fixes/improvements. See individual commit messages for more information.
> Assorted style fixes

- pootle/static/css/user.css
- pootle/static/js/shared/components/AutoIcon.js
- pootle/static/js/user/app.js
- pootle/static/js/user/components/UserProfileForm.js
A grab bag of styling improvements for user's public profile and its editor.
Also fixes an issue with Gravatar in the profile editor (one needs to pass md5 hash, not a raw email address, to the Avatar component since the code of the Avatar component has changed recently).
> User profile page fixes

- pootle/static/js/browser/components/ProgressBar.js
- pootle/static/js/browser/components/TopContributorsTable.js
- pootle/static/js/shared/components/AboutDialog.js
- pootle/static/js/shared/components/KeyboardHelpDialog.js
> Add i18n markers to new and some existing components (fix #56)

- pootle/static/js/browser.js
- pootle/static/js/utils.js
This PR simplifies and cleans up the code around the creation of selectable breadcrumbs' dropdowns. 
Please test on your side @iafan.
> Cleanup select creation code

- requirements/base.txt
- requirements/travis.txt
These refer to old or unused features.
> Cleanup: remove no longer used dependencies

- CHANGES.md
- pootle/apps/pootle_store/unit/filters.py
- pootle/static/css/select2-pootle.css
- pootle/static/js/editor/app.js
- pootle/templates/editor/_filters.html
- tests/search.py
- tests/views/get_units.py
Allows selecting and filtering by an entire group of checks in the editor.
> Editor: allow filtering by check categories

- pootle/apps/pootle_store/unit/search.py
> Cleanup: humanize keyword argument construction

- pootle/runner.py
Some remnants which were still pending a rename.
> Cleanup: adjust name

- pootle/apps/pootle_store/managers.py
- pytest_pootle/fixtures/models/store.py
- tests/formats/util.py
- tests/models/store.py
This is FS-related code which is unused.
> Cleanup: remove dead code

- tests/core/utils/json.py
These should have been part of 2d5af74.
> Add missing tests for `remove_empty_from_dict`

- pytest_pootle/fixtures/views.py
- tests/models/submission.py
- tests/views/admin.py
- tests/views/disabled_project.py
- tests/views/get_contributors.py
- tests/views/get_edit_unit.py
- tests/views/get_qc_stats.py
- tests/views/get_stats.py
- tests/views/get_units.py
- tests/views/project.py
- tests/views/unit.py
- tests/views/user.py
This is basically a continuation of 77deb8c.
> Tests: fix login for view tests

- pootle/core/mixins/treeitem.py
- pootle/core/views/browse.py
A couple of minor cleanups on `TreeItem` spotted while reading through.
> Minor `TreeItem` cleanups

- pytest_pootle/fixtures/cache.py
- pytest_pootle/fixtures/revision.py
- pytest_pootle/fixtures/site.py
- tests/views/browse.py
- tests/views/translate.py
This organizes things a bit around flushing caches in tests.
> Tests: cleanup cache fixtures

- pytest_pootle/fixtures/cache.py
- tests/data/snapshots/test_browse/admin/_language0_.context.json
- tests/data/snapshots/test_browse/admin/_language0_project0_.context.json
- tests/data/snapshots/test_browse/admin/_language0_project0_store0.po.context.json
- tests/data/snapshots/test_browse/admin/_language0_project0_subdir0_.context.json
- tests/data/snapshots/test_browse/admin/_language0_project0_subdir0_store4.po.context.json
- tests/data/snapshots/test_browse/admin/_projects_.context.json
- tests/data/snapshots/test_browse/admin/_projects_project0_.context.json
- tests/data/snapshots/test_browse/member/_language0_.context.json
- tests/data/snapshots/test_browse/member/_language0_project0_.context.json
- tests/data/snapshots/test_browse/member/_language0_project0_store0.po.context.json
- tests/data/snapshots/test_browse/member/_language0_project0_subdir0_.context.json
- tests/data/snapshots/test_browse/member/_language0_project0_subdir0_store4.po.context.json
- tests/data/snapshots/test_browse/member/_projects_.context.json
- tests/data/snapshots/test_browse/member/_projects_project0_.context.json
- tests/data/snapshots/test_browse/member2/_language0_.context.json
- tests/data/snapshots/test_browse/member2/_language0_project0_.context.json
- tests/data/snapshots/test_browse/member2/_language0_project0_store0.po.context.json
- tests/data/snapshots/test_browse/member2/_language0_project0_subdir0_.context.json
- tests/data/snapshots/test_browse/member2/_language0_project0_subdir0_store4.po.context.json
- tests/data/snapshots/test_browse/member2/_projects_.context.json
- tests/data/snapshots/test_browse/member2/_projects_project0_.context.json
- tests/data/snapshots/test_browse/nobody/_language0_.context.json
- tests/data/snapshots/test_browse/nobody/_language0_project0_.context.json
- tests/data/snapshots/test_browse/nobody/_language0_project0_store0.po.context.json
- tests/data/snapshots/test_browse/nobody/_language0_project0_subdir0_.context.json
- tests/data/snapshots/test_browse/nobody/_language0_project0_subdir0_store4.po.context.json
- tests/data/snapshots/test_browse/nobody/_projects_.context.json
- tests/data/snapshots/test_browse/nobody/_projects_project0_.context.json
- tests/views/browse.py
~~This allows us to bring back stats data for tests, which is absolutely required.~~
Apparently my local test cache was pre-populated so this PR is far from complete. I still need to figure out a good way to ensure we have access to stats data.
> Tests: ensure stats are available

- pootle/apps/pootle_store/unit/results.py
> Editor: provide consistent language names

- pootle/core/views/api.py
- tests/core/views.py
This code was added to support multiple file types in the admin UI, which is no
longer relevant.
> APIView: remove unused code

- pootle/static/css/editor.css
- pootle/static/js/editor/app.js
- pootle/templates/editor/_actions.html
This is a bunch of editor-related UI fixes/improvements spotted after releasing the new editor code. See individual commit messages for in-depth description.
> Grab bag of editor fixes

- pootle/apps/pootle_app/models/permissions.py
This was introduced for the news feature, which is long gone.
> Cleanup: remove dead parameter

- requirements/base.txt
> Requirements: TTK bump

- pootle/static/js/editor/app.js
See https://github.com/evernote/zing/issues/166#issuecomment-274971510
for a full description of the new behavior
> Editor: Improve UX for 'unit(s) not found' cases (fix #166)

- docs/server/settings.rst
- pootle/apps/pootle_store/views.py
- pootle/settings/30-site.conf
- pootle/settings/90-local.conf.template
- tests/settings.py
If used, we can revisit it later and implement it via notifications.
> Cleanup: remove unused feedback emailing

- pootle/core/views/api.py
This is a more idiomatic approach to overriding form data rather than the
previous `form_save()` method.
> APIView: allow overriding form kwargs

- tests/views/api/duedate.py
The branch is now on Django 1.10 so this needed to be adjusted.
> Tests: `is_anonymous` is now a property

- pootle/core/models/snapshot.py
- pootle/views/api/duedate.py
This way the client can perform actions on specific resources.
> DueDateAPIView: also return id

- CHANGES.md
- pootle/static/js/admin/app.js
- pootle/static/js/package.json
- pootle/static/js/shared/components/CodeMirror.js
- pootle/static/js/webpack.config.js
We'll delay the switch to Webpack2 until we move our production instance to a new server.
> Revert webpack2

- pootle/static/js/admin/duedates/components/DueDateContainer.js
- tests/data/snapshots/test_duedate_post/admin/_language0_.context.json
- tests/data/snapshots/test_duedate_post/admin/_language0_project0_.context.json
- tests/data/snapshots/test_duedate_post/admin/_language0_project0_store0.po.context.json
- tests/data/snapshots/test_duedate_post/admin/_language0_project0_subdir0_.context.json
- tests/data/snapshots/test_duedate_post/admin/_language0_project0_subdir0_store4.po.context.json
- tests/data/snapshots/test_duedate_post/admin/_projects_project0_.context.json
- tests/data/snapshots/test_duedate_post/admin/_projects_project0_store0.po.context.json
- tests/data/snapshots/test_duedate_post/admin/_projects_project0_subdir0_.context.json
- tests/data/snapshots/test_duedate_post/admin/_projects_project0_subdir0_store4.po.context.json
- tests/data/snapshots/test_duedate_update/admin/_language0_.context.json
- tests/data/snapshots/test_duedate_update/admin/_language0_project0_.context.json
- tests/data/snapshots/test_duedate_update/admin/_language0_project0_store0.po.context.json
- tests/data/snapshots/test_duedate_update/admin/_language0_project0_subdir0_.context.json
- tests/data/snapshots/test_duedate_update/admin/_language0_project0_subdir0_store4.po.context.json
- tests/data/snapshots/test_duedate_update/admin/_projects_project0_.context.json
- tests/data/snapshots/test_duedate_update/admin/_projects_project0_store0.po.context.json
- tests/data/snapshots/test_duedate_update/admin/_projects_project0_subdir0_.context.json
- tests/data/snapshots/test_duedate_update/admin/_projects_project0_subdir0_store4.po.context.json
No need to parse them to integers anymore.
> DueDateContainer: due on timestamps are integers

- pootle/static/js/browser/components/BrowserTableRow.js
- pootle/static/js/shared/utils/url.js
This PR factors out the translation URL generation from browsing pages into a reusable utility function.
> Cleanup: refactor translation URL generation

- pootle/static/js/admin/duedates/components/DueDatePicker.css
- pootle/static/js/admin/duedates/components/DueDatePicker.js
- pootle/static/js/package.json
This is using react-day-picker. The styles are almost verbatim based on
the library's example styles, changing a few colors here and there.
> Due Date widget: incorporate date picker

- pootle/static/js/admin/duedates/components/DueDateWidget.js
- pootle/static/js/shared/components/Dropdown.css
- pootle/static/js/shared/components/Dropdown.js
The dropdown logic becomes reusable for other contexts and likewise
unifies the look & feel to match other dropdowns such as that used in
the search options.
> DueDateWidget: refactor dropdown logic, restyle

- pootle/static/js/admin/duedates/components/DueDatePicker.js
The due date picker was using ISO-formatted date strings as part of its
state, which were then used to create `Date` objects to be used in the
`DatePicker` component.
This turned out to be problematic because `new Date('YYYY-MM-dd')` sets
a date at midnight time in UTC. At the same time, react-day-picker works
with local times internally (e.g. `date.getDate()` instead of
`date.getUTCDate()`), and feeding dates set at UTC midnight time to the
library would result in the day before the selected one being displayed.
So instead of keeping track of a `YYYY-MM-dd` date in the component's
state, we store the date object provided by react-day-picker. At
initialization, the timestamp value is used to generate a `Date` object.
The `YYYY-MM-dd` format is kept as-is for communicating changes to the …
> DueDatePicker: fix day selection for dates with negative UTC offset

- pootle/apps/pootle_misc/context_processors.py
- pootle/static/js/admin/duedates/components/DueDatePicker.css
- pootle/static/js/admin/duedates/components/DueDatePicker.js
- pootle/static/js/admin/duedates/components/DueDateWidget.js
- pootle/static/js/admin/duedates/utils.js
- pootle/templates/layout.html
This will display either a placeholder message, or the full date and
time of the set due date.
> DueDatePicker: display selection hints

- pootle/static/js/browser/components/DetailedStats.js
- pootle/static/js/browser/components/Stats.js
- pootle/static/js/stats.js
- pootle/templates/browser/index.html
Most of the rendering logic is now declarative.
> Refactor: gather individually-rendered components in `DetailedStats`

- pootle/static/css/style.css
- pootle/static/js/browser/components/DetailedStats.js
- pootle/static/js/browser/components/StatsSummary.js
- pootle/static/js/stats.js
- pootle/templates/browser/index.html
More work towards lifting state up.
> Refactor: move toggling functionality into a component

- pootle/static/js/admin/duedates/components/DueDatePicker.css
- pootle/static/js/admin/duedates/components/DueDatePicker.js
This includes:
* Separation in the UI between manually-selected days and committed (saved) days
* Fixes for navigational items disappearing
* Hints are dynamic now
* Improved handling for cases where there is no due date set
> Various date picker fixes

- .gitignore
- pootle/static/css/actions.css
- pootle/static/js/browser/components/TaskItem.js
See individual commit messages. @julen please review/merge
> A few styling inprovements

- pootle/static/css/actions.css
- pootle/static/css/zing-icons.css
- pootle/static/js/admin/duedates/components/DueDatePicker.css
- pootle/static/js/admin/duedates/components/DueDatePicker.js
- pootle/static/js/shared/components/DropdownToggle.js
The idea behind the layout changes, apart from stylistic tweaks, was to make sure the dialog doesn't change it size and the controls don't jump around on switching dates. @julen please review/merge
> Adjust due date picker styling/wording/layout

- pootle/apps/pootle_store/updater.py
- tests/models/store.py
There's no functional change here but reduces some readability pain experienced while debugging.
> Cleanup: readability

- pytest_pootle/fixtures/models/store.py
While debugging I found that these fixtures are now unused.
> Cleanup: remove unused fixtures

- pytest_pootle/fixtures/models/store.py
- tests/models/store.py
It removes unused parameters and renames a few parameters for easier understanding.
> Test cleanups

- pytest_pootle/fixtures/models/store.py
Also make it more explicit so that less guesswork is involved.
> Cleanup: document UPDATE_STORE_TESTS

- pootle/apps/pootle_store/diff.py
It turns out this is being used in some tests, so let's bring it back
for the time being. The reason this didn't break is that the TTK and DB
stores almost entirely share the API surface being used here.
> StoreDiff: bring back store support as a source

- docs/server/installation.rst
- docs/server/settings.rst
- pootle/apps/pootle_app/management/commands/initdb.py
- pootle/settings/90-local.conf.template
- pootle/settings/95-outro.conf
- tests/commands/initdb.py
- tests/conftest.py
Here are some fixes for the installation docs. These are by no means fully working yet, but it's better than before one step at a time...
> Installation doc fixes

- pootle/apps/accounts/migrations/0006_auto_add_gbp.py
- pootle/apps/accounts/models.py
(This should probably be done in a different way (e.g. via a `ForeignKey`) but let's leave it as-is for now.)
> Invoices: add support for GBP currency

- pootle/settings/91-travis.conf
> Tests: force strict mode in MySQL

- CHANGES.md
- pootle/static/js/admin/app.js
- pootle/static/js/package.json
- pootle/static/js/shared/components/CodeMirror.js
- pootle/static/js/webpack.config.js
This PR upgrades our webpack config and dependencies to the latest stable version.
(Not to be merged right away, still need to do some testing around dynamic imports.)
> Upgrade webpack

- CHANGES.md
- pootle/static/js/editor/UnitList.js
> Editor: allow re-opening last unit

- docs/developers/browsers.rst
- pootle/static/js/editor/utils/RawFontAware.js
- pootle/static/js/editor/utils/highlight.js
- pootle/static/js/shared/utils/cookie.js
- pootle/static/js/shared/utils/dom.js
- pootle/static/js/shared/utils/i18n.js
- pootle/static/js/shared/utils/url.js
This removes IE-specific hacks.
> Explicitly drop compatibility with IE11

- pootle/apps/pootle_profile/forms.py
- pootle/apps/pootle_profile/views.py
- pootle/static/js/package.json
- pootle/static/js/shared/api/UserAPI.js
- pootle/static/js/user/app.js
- pootle/static/js/user/components/UserProfileEdit.js
- pootle/static/js/user/components/UserProfileForm.js
- pootle/templates/user/profile.html
It also removes the dependency on the md5 module.
Before:
```
user/app.bundle.js  78.6 kB      10  [emitted]  user
```
After:
```
user/app.bundle.js  66.2 kB      10  [emitted]  user
```
> User profile: get rid of Backbone dependency

- .travis.yml
- pootle/static/js/editor/utils/highlight.js
- requirements/_docs.txt
Trying to adjust Travis conf to the [new environment updates](https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images)...
> Travis: update to the new environment

- CHANGES.md
- pootle/static/js/package.json
...to their latest stable versions.
> Upgrade Babel versions

- pootle/static/js/auth/components/AuthContent.js
- pootle/static/js/auth/components/PasswordResetForm.js
- pootle/static/js/auth/components/RequestPasswordResetForm.js
- pootle/static/js/auth/components/SignInForm.js
- pootle/static/js/auth/components/SignUpForm.js
- pootle/static/js/auth/components/SocialVerification.js
- pootle/static/js/auth/index.js
- pootle/static/js/editor/app.js
- pootle/static/js/editor/components/RawFontTextarea.js
- pootle/static/js/editor/formats/FormatLoader.js
- pootle/static/js/editor/index.js
- pootle/static/js/editor/mt/MTProvider.js
- pootle/static/js/editor/utils/font.js
- pootle/static/js/package.json
- pootle/static/js/reducers.js
- pootle/static/js/reports/app.js
- pootle/static/js/search.js
- pootle/static/js/shared/api/DueDateAPI.js
- pootle/static/js/shared/utils/i18n.js
- pootle/static/js/stats.js
- pootle/static/js/user/components/UserProfileForm.js
This is available in the browsers we support.
> Cleanup: switch to native Object.assign

- CHANGES.md
- pootle/apps/staticpages/forms.py
- pootle/apps/staticpages/migrations/0003_auto_rm_url_field.py
- pootle/apps/staticpages/models.py
- pootle/apps/staticpages/views.py
- pootle/templates/admin/staticpages/_form.html
- pootle/templates/admin/staticpages/_table.html
- pytest_pootle/data/data_dump.json
This has been unused for a while.
> Staticpages: drop URL field

- pootle/static/css/welcome.css
- pootle/static/js/common.js
- pootle/static/js/welcome/components/Hero.js
- pootle/templates/welcome.html
> Welcome page: reorganize in a single Hero component

- pootle/runner.py
The others are not important in this context.
> runner: only report Zing version

- pootle/apps/contact/forms.py
This reverts commit 71d2b47239962e9dc0ca17e406dc3f4012d0a79c.
The required fixes were already made upstream and we use an updated
package.
> Revert "Work around ContactForm's buggy Django 1.10 support"

- CHANGES.md
- docs/features/translation_memory.rst
- docs/server/settings.rst
- pootle/apps/pootle_app/management/commands/update_tmserver.py
- pootle/checks.py
- pootle/core/search/backends/elasticsearch.py
- pootle/core/search/base.py
- pootle/core/search/broker.py
- pootle/settings/90-local.conf.template
- tests/commands/update_tmserver.py
* Simplifies the TM to be fed and auto-updated from the DB
* There's a single TM server
* Less configuration with sane defaults
> TM: simplify to a single server

- .travis.yml
- tox.ini
Fixes this minor inconsistency.
> Travis: fix Django version number

- CHANGES.md
- pootle/static/js/editor/components/Editor.js
- pootle/static/js/editor/components/plurr/CaretButton.js
- pootle/static/js/editor/components/plurr/CaretIcon.js
- pootle/static/js/editor/components/plurr/PlurrEditor.js
- pootle/static/js/editor/components/plurr/PlurrHelp.js
- pootle/static/js/editor/components/plurr/PlurrInput.js
- pootle/static/js/editor/components/plurr/PlurrParamsForm.js
- pootle/static/js/editor/components/plurr/PlurrPreview.js
- pootle/static/js/editor/components/plurr/PlurrPreviewOutput.js
- pootle/static/js/editor/containers/EditorContainer.js
- pootle/static/js/editor/utils/index.js
- pootle/static/js/editor/utils/strings.js
- pootle/templates/editor/units/edit.html
Pulling it in from the internal repo.
> Editor: incorporate live editor for Plurr strings

- docs/ref-commands.md
> Docs: mention `--generate-report` flag

- CHANGES.md
- docs/ref-settings.md
- pootle/apps/pootle_misc/context_processors.py
- pootle/settings/10-base.conf
- pootle/settings/90-dev-local.conf.sample
- pootle/templates/layout.html
This is something 3rd parties can easily implement via custom context processors.
> Settings: externalize `ZING_INSTANCE_ID`

- CHANGES.md
- docs/ref-settings.md
- pootle/apps/pootle_misc/context_processors.py
- pootle/apps/staticpages/context_processors.py
- pootle/settings/40-apps.conf
- pootle/settings/50-project.conf
- pootle/static/js/agreement.js
- pootle/static/js/helpers.js
The entire approach should be revisited but in the meantime let's not cause confusion with the setting.
Refs. #318.
> Cleanup: move legalpage prefixes to constant

- pootle/apps/pootle_app/forms.py
- tests/forms/user.py
...just to make sure we don't shoot ourselves in the foot.
> User: make linkedin validation more robust + tests

- CHANGES.md
- pootle/static/css/breadcrumbs.css
- pootle/static/js/browser.js
This way looking for a particular locale becomes easier.
> Browser: match locale codes in languages dropdown

- CHANGES.md
- pootle/apps/reports/models/invoice.py
- pootle/apps/reports/models/payment_email.py
- pootle/apps/reports/reporters.py
- pootle/templates/invoices/no_invoice_message.html
- tests/models/invoice.py
This PR fixes an issue where the carried over balance wouldn't be properly displayed on emails.
> Invoices: fix display of carried over balance

- pootle/apps/reports/models/invoice.py
- pootle/apps/reports/models/payment_email.py
- pootle/templates/invoices/no_invoice_message.html
- tests/models/invoice.py
Just to make it clear what we are referring to with carry-overs and corrections.
> Cleanups around invoices naming etc.

- CHANGES.md
- pootle/apps/pootle_translationproject/models.py
- tests/models/translationproject.py
> Do not create/scan TPs upon creation via UI

- pootle/apps/pootle_app/forms.py
- pootle/apps/pootle_profile/forms.py
> Cleanup: reuse logic across user forms

- pootle/static/js/package-lock.json
- pootle/static/js/package.json
So that subsequent installs generate identical node_modules trees.
> Incorporate package-lock.json

- pootle/static/js/package-lock.json
- pootle/static/js/package.json
Note the noise in the package-lock.json file is due to using a newer npm
version.
> Deps: remove unused lodash

- .travis.yml
- pootle/__init__.py
- pootle/apps/pootle_app/management/__init__.py
- pootle/core/mixins/__init__.py
- pootle/core/search/__init__.py
- pootle/core/views/__init__.py
...and make sure other services are running.
> Travis: force Python 2.7

- pootle/checks.py
- requirements/base.txt
> Reqs: use django 1.11.26

- requirements/base.txt
> Reqs: use django-allauth 0.40.0

- requirements/base.txt
> Reqs: use django-contact-form 1.7.0

- requirements/base.txt
> Reqs: use django-contrib-comments 1.9.1

- pootle/settings/40-apps.conf
- requirements/base.txt
> Reqs: use django-statici18n 1.8.3

- requirements/base.txt
- requirements/tests.txt
> Reqs: use python-dateutil 2.8.1

- requirements/base.txt
> Reqs: use lxml 4.4.2

- requirements/tests.txt
> Reqs: use factory-boy 2.12.0

- requirements/tests.txt
- tests/conftest.py
- tests/env.py
- tests/fixtures/models/permission.py
- tests/fixtures/models/statistics.py
- tests/fixtures/models/user.py
> Reqs: use pytest 4.6.0 and pytest-django 3.7.0

- requirements/base.txt
> Reqs: use django-redis 4.10.0

- requirements/deploy.txt
- requirements/travis.txt
> Reqs: update database dependencies

- requirements/_lint.txt
> Reqs: update lint-related dependencies

- pootle/apps/pootle_app/management/commands/retry_failed_jobs.py
- pootle/apps/pootle_app/views/admin/dashboard.py
- pootle/core/mixins/treeitem.py
- requirements/base.txt
- requirements/tests.txt
- tests/env.py
- tests/models/store.py
- tests/settings.py
- tests/views/timeline.py
> Reqs: upgrade fakeredis, django-redis, django-rq, and rq

- requirements/base.txt
> Reqs: use translate-toolkit 2.4.0

- pootle/middleware/errorpages.py
- pootle/settings/25-logging.conf
- requirements/deploy.txt
> Reqs: switch to sentry-sdk

- .travis.yml
- docs/ref-settings.md
- pootle/apps/pootle_app/management/commands/update_tmserver.py
- pootle/core/search/backends/elasticsearch.py
- pootle/settings/90-local.conf.template
- requirements/base.txt
> Reqs: use elasticsearch 7.x

- pootle/apps/accounts/managers.py
- pootle/apps/accounts/models.py
- pootle/apps/pootle_language/views.py
- pootle/apps/pootle_misc/checks.py
- pootle/apps/pootle_project/views.py
- pootle/apps/pootle_store/fields.py
- pootle/apps/pootle_store/models.py
- pootle/apps/pootle_store/views.py
- pootle/apps/pootle_translationproject/views.py
- pootle/apps/reports/models/invoice.py
- pootle/core/checks/checker.py
- pootle/core/utils/json.py
- pootle/core/utils/version.py
- pootle/middleware/errorpages.py
- pootle/views/api/duedate.py
- requirements/base.txt
> Upgrade to Django 3

- requirements/base.txt
- requirements/tests.txt
- tests/commands/flush_cache.py
- tests/commands/generate_invoices.py
- tests/commands/merge_user.py
- tests/commands/purge_user.py
- tests/commands/update_tmserver.py
- tests/commands/verify_user.py
- tests/fixtures/models/translation_project.py
- tests/models/invoice.py
- tox.ini
> Upgrade python dependencies

- pootle/checks.py
- requirements/base.txt
* Fixes gettext calls
* Fixes wording for some strings
* Removes library version checks (they are covered by requirements files)
> Checks: fixes and cleanups

- pootle/apps/pootle_app/management/commands/update_tmserver.py
- pootle/core/search/backends/elasticsearch.py
Now each language has its own index, and update_tmserver needs to cater for that.
> TM: fix update_tmserver to account for multiple indices

- pootle/core/views/export.py
> Uplift export view results limit

- CHANGES.md
- pootle/models/duedate.py
- pootle/models/task.py
- tests/data/snapshots/test_get_tasks/admin/context.json
- tests/data/snapshots/test_get_tasks/member/context.json
- tests/data/snapshots/test_get_tasks_permissions/admin/context.json
> Tasks: sort by due date

- CHANGES.md
- pootle/apps/reports/models/invoice.py
- tests/models/invoice.py
> Invoices: avoid zero carry-overs

- CHANGES.md
- pootle/apps/pootle_misc/checks.py
- tests/data/snapshots/test_translate/admin/_language0_project0_translate_.context.json
- tests/data/snapshots/test_translate/admin/_language0_project0_translate_empty_dir0_.context.json
- tests/data/snapshots/test_translate/admin/_language0_project0_translate_empty_dir1_store6.po.context.json
- tests/data/snapshots/test_translate/admin/_language0_project0_translate_store0.po.context.json
- tests/data/snapshots/test_translate/admin/_language0_project0_translate_subdir0_.context.json
- tests/data/snapshots/test_translate/admin/_language0_project0_translate_subdir0_store4.po.context.json
- tests/data/snapshots/test_translate/admin/_language0_translate_.context.json
- tests/data/snapshots/test_translate/admin/_projects_project0_translate_.context.json
- tests/data/snapshots/test_translate/admin/_projects_project0_translate_empty_dir1_store6.po.context.json
- tests/data/snapshots/test_translate/admin/_projects_project0_translate_store0.po.context.json
- tests/data/snapshots/test_translate/admin/_projects_project0_translate_subdir0_.context.json
- tests/data/snapshots/test_translate/admin/_projects_project0_translate_subdir0_store4.po.context.json
- tests/data/snapshots/test_translate/admin/_projects_translate_.context.json
- tests/data/snapshots/test_translate/member/_language0_project0_translate_.context.json
- tests/data/snapshots/test_translate/member/_language0_project0_translate_empty_dir0_.context.json
- tests/data/snapshots/test_translate/member/_language0_project0_translate_empty_dir1_store6.po.context.json
- tests/data/snapshots/test_translate/member/_language0_project0_translate_store0.po.context.json
- tests/data/snapshots/test_translate/member/_language0_project0_translate_subdir0_.context.json
- tests/data/snapshots/test_translate/member/_language0_project0_translate_subdir0_store4.po.context.json
- tests/data/snapshots/test_translate/member/_language0_translate_.context.json
- tests/data/snapshots/test_translate/nobody/_language0_project0_translate_.context.json
- tests/data/snapshots/test_translate/nobody/_language0_project0_translate_empty_dir0_.context.json
- tests/data/snapshots/test_translate/nobody/_language0_project0_translate_empty_dir1_store6.po.context.json
- tests/data/snapshots/test_translate/nobody/_language0_project0_translate_store0.po.context.json
- tests/data/snapshots/test_translate/nobody/_language0_project0_translate_subdir0_.context.json
- tests/data/snapshots/test_translate/nobody/_language0_project0_translate_subdir0_store4.po.context.json
- tests/data/snapshots/test_translate/nobody/_language0_translate_.context.json
- tests/misc/checks.py
> Checks: implement ellipsis check

- requirements/base.txt
- requirements/deploy.txt
Updates Django and sentry-sdk to latest bugfix releases.
> Requirements updates

- CHANGES.md
- pootle/apps/pootle_store/unit/search.py
- pootle/core/views/export.py
> Export view: increase results limit to 1000 rows

- Makefile
- setup.py
Refs. pypa/setuptools#1684, pytest-dev/pytest#5534.
> Tests: remove deprecated `setup.py test`

- CHANGES.md
- pootle/apps/pootle_app/assets.py
- pootle/static/js/.babelrc
- pootle/static/js/.eslintrc.js
- pootle/static/js/editor/app.js
- pootle/static/js/package-lock.json
- pootle/static/js/package.json
- pootle/static/js/webpack.config.js
- pootle/templates/layout.html
~Still WIP because some jQuery plugin dependencies are not playing well with the new config...~
Also updates to Babel 7 along the way.
Fixes #449.
> Upgrade to webpack 4

- pootle/static/js/package-lock.json
- pootle/static/js/package.json
Also helps upgrade some dependencies with security issues.
> Upgrade to latest Mocha

- CHANGES.md
- pootle/static/css/actions.css
- pootle/static/css/editor.css
- pootle/static/css/navbar.css
- pootle/static/css/reports.css
- pootle/static/css/scores.css
- pootle/static/css/style.css
- pootle/static/css/user.css
- pootle/static/css/welcome.css
- pootle/static/css/zing-icons.css
- pootle/static/js/admin/duedates/components/DueDatePicker.css
- pootle/static/js/admin/general/components/LiveEditor.css
- pootle/static/js/package-lock.json
- pootle/static/js/package.json
- pootle/static/js/stylelint.json
Upgrades stylelint, adjusts some rules and fixes reported issues.
> Stylelint upgrade

- pootle/templates/help/quality_checks.html
new attempt at previous changes requested. Adds CSS styling to the quality checks static page.
> Benjamimo1 fix/add css qc
